// Example output generated by TypeScriptApiStubGenerator.
import { createApi, type ApiRoute } from '@trunkjs/api-stub';

/**
 * Public user returned by the backend.
 * @php App\Api\Dto\User
 */
export interface User {
  /** Numeric database id. */
  id: number;
  /** Display name. */
  name: string;
}

/**
 * Payload accepted by the user endpoint.
 * @php App\Api\Dto\UserInput
 */
export interface UserInput {
  name: string;
}

export type ApiRoutes = {
  'User.Get': ApiRoute<{ userId?: number }, { locale?: string }, never, User, 'GET'>;
  'User.Item': ApiRoute<{ userId?: number }, { locale?: string }, UserInput, User, 'GET' | 'POST' | 'PATCH'>;
};

// This is the only generated runtime data: method(s) + path.
export const routes = {
  'User.Get': ['GET', '/api/users/{userId}'],
  'User.Item': [['GET', 'POST', 'PATCH'], '/api/users/{userId}'],
} as const;

export const API = createApi<ApiRoutes>(routes);

// Consumers can configure the generated API without regenerating it:
// const api = API.with({ baseUrl: '/backend', params: { userId: 42 } });
// await api.User.Get.request();
// api.User.Get.path();
// api.User.Get.url();
