// Example output generated by TypeScriptApiStubGenerator.
import { createApi, type ApiRoute } from '@trunkjs/api-stub';

/** Public user returned by the backend. @php App\Api\Dto\User */
export interface User { id: number; name: string; }

export type ApiRoutes = {
  'User.Get': ApiRoute<{ userId: number }, { locale: string }, never, User, 'GET'>;
};

export const routes = {
  'User.Get': ['GET', '/api/users/{userId}'],
} as const;

const baseAPI = createApi<ApiRoutes>(routes);
export type ApiConfig = Parameters<typeof baseAPI.with>[0];
export const createAPI = (config?: ApiConfig) => config ? baseAPI.with(config) : baseAPI;
export const API = baseAPI;

// Best practice: generated source contains no deployment-specific host.
// Same origin:
//   await API.User.Get.with({ params: { userId: 42 }, query: { locale: 'de' } }).request();
// Build-time environment (e.g. Vite):
//   const api = createAPI({ baseUrl: import.meta.env.VITE_API_URL });
// Runtime config injected by the backend into HTML:
//   const api = createAPI({ baseUrl: window.APP_CONFIG.apiBaseUrl });
