<?php

declare(strict_types=1);

namespace Brace\SpaServe\Codegen;

use Phore\Schema\Schema\ClassSchema;
use Phore\Schema\Schema\Type\ArraySchemaType;
use Phore\Schema\Schema\Type\ClassReferenceSchemaType;
use Phore\Schema\Schema\Type\IntersectionSchemaType;
use Phore\Schema\Schema\Type\PrimitiveSchemaType;
use Phore\Schema\Schema\Type\SchemaType;
use Phore\Schema\Schema\Type\UnionSchemaType;

/**
 * Generates the small runtime route table and compile-time types consumed by
 * @trunkjs/api-stub. The generated JavaScript runtime stays intentionally tiny.
 */
final class TypeScriptApiStubGenerator
{
    /**
     * @param list<array{name:string, path:string, methods:list<string>, response:SchemaType, body?:SchemaType|null}> $routes
     * @param list<ClassSchema> $classes
     */
    public function generate(array $routes, array $classes = []): string
    {
        $out = [
            "// Generated by brace/mod-spaserve. Do not edit.",
            "import { createApi, type ApiRoute } from '@trunkjs/api-stub';",
            '',
        ];

        foreach ($classes as $class) {
            $out[] = $this->renderClass($class);
            $out[] = '';
        }

        $out[] = 'export type ApiRoutes = {';
        foreach ($routes as $route) {
            $body = isset($route['body']) && $route['body'] instanceof SchemaType
                ? $this->renderType($route['body'])
                : 'never';
            $methods = implode(' | ', array_map(fn (string $method): string => $this->quote(strtoupper($method)), $route['methods']));
            $out[] = sprintf(
                "  %s: ApiRoute<Record<string, unknown>, Record<string, unknown>, %s, %s, %s>;",
                $this->quote($route['name']),
                $body,
                $this->renderType($route['response']),
                $methods,
            );
        }
        $out[] = '};';
        $out[] = '';
        $out[] = 'export const routes = {';
        foreach ($routes as $route) {
            $methods = count($route['methods']) === 1
                ? $this->quote(strtoupper($route['methods'][0]))
                : '[' . implode(', ', array_map(fn (string $method): string => $this->quote(strtoupper($method)), $route['methods'])) . ']';
            $out[] = sprintf("  %s: [%s, %s],", $this->quote($route['name']), $methods, $this->quote($route['path']));
        }
        $out[] = '} as const;';
        $out[] = '';
        $out[] = 'export const API = createApi<ApiRoutes>(routes);';
        $out[] = '';

        return implode("\n", $out);
    }

    private function renderClass(ClassSchema $class): string
    {
        $out = [];
        $out[] = '/**';
        if ($class->description !== '') {
            foreach (preg_split('/\R/', $class->description) ?: [] as $line) {
                $out[] = ' * ' . $line;
            }
        }
        $out[] = ' * @php ' . $class->className;
        $out[] = ' */';
        $out[] = 'export interface ' . $class->shortName . ' {';
        foreach ($class->properties as $property) {
            if ($property->description !== '') $out[] = '  /** ' . str_replace('*/', '* /', $property->description) . ' */';
            $optional = $property->hasDefaultValue ? '?' : '';
            $type = $this->renderType($property->type) . ($property->allowsNull ? ' | null' : '');
            $out[] = sprintf('  %s%s: %s;', $property->name, $optional, $type);
        }
        $out[] = '}';
        return implode("\n", $out);
    }

    private function renderType(SchemaType $type): string
    {
        if ($type instanceof PrimitiveSchemaType) {
            return match ($type->getKind()) {
                'int', 'float', 'numeric' => 'number',
                'bool' => 'boolean',
                'null' => 'null',
                'mixed' => 'unknown',
                'false', 'true' => $type->getKind(),
                'string' => 'string',
                default => 'unknown',
            };
        }

        if ($type instanceof ArraySchemaType) {
            $value = $this->renderType($type->valueType);
            return $type->arrayKind === ArraySchemaType::KIND_MAP
                ? 'Record<string, ' . $value . '>'
                : 'Array<' . $value . '>';
        }

        if ($type instanceof ClassReferenceSchemaType) {
            $data = $type->toArray();
            $name = (string) ($data['className'] ?? 'unknown');
            $parts = explode('\\', $name);
            return end($parts) ?: 'unknown';
        }

        if ($type instanceof UnionSchemaType || $type instanceof IntersectionSchemaType) {
            $data = $type->toArray();
            $types = $data['types'] ?? [];
            $operator = $type instanceof UnionSchemaType ? ' | ' : ' & ';
            return implode($operator, array_map(fn (array $item): string => $this->renderArrayType($item), $types));
        }

        if ($type instanceof ClassSchema) return $type->shortName;
        return 'unknown';
    }

    /** @param array<string,mixed> $type */
    private function renderArrayType(array $type): string
    {
        $kind = $type['kind'] ?? 'mixed';
        return match ($kind) {
            'int', 'float', 'numeric' => 'number',
            'bool' => 'boolean',
            'string' => 'string',
            'null' => 'null',
            'true', 'false' => $kind,
            'class-reference' => basename(str_replace('\\', '/', (string) ($type['className'] ?? 'unknown'))),
            default => 'unknown',
        };
    }

    private function quote(string $value): string
    {
        return json_encode($value, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
    }
}
