<?php

declare(strict_types=1);

namespace Brace\SpaServe\Codegen;

use Phore\Schema\Schema\ClassSchema;
use Phore\Schema\Schema\Type\ArraySchemaType;
use Phore\Schema\Schema\Type\ClassReferenceSchemaType;
use Phore\Schema\Schema\Type\IntersectionSchemaType;
use Phore\Schema\Schema\Type\PrimitiveSchemaType;
use Phore\Schema\Schema\Type\SchemaType;
use Phore\Schema\Schema\Type\UnionSchemaType;

final class TypeScriptApiStubGenerator
{
    /** @param list<array{name:string,path:string,methods:list<string>,response:SchemaType,body?:SchemaType|null,pathParams?:array<string,SchemaType>,queryParams?:array<string,SchemaType>}> $routes @param list<ClassSchema> $classes */
    public function generate(array $routes, array $classes = []): string
    {
        usort($routes, static fn(array $a, array $b): int => $a['name'] <=> $b['name']);
        usort($classes, static fn(ClassSchema $a, ClassSchema $b): int => $a->className <=> $b->className);
        $out = ['// Generated by brace/mod-spaserve. Do not edit.', "import { createApi, type ApiRoute } from '@trunkjs/api-stub';", ''];
        foreach ($classes as $class) { $out[] = $this->renderClass($class); $out[] = ''; }
        $out[] = 'export type ApiRoutes = {';
        foreach ($routes as $route) {
            $body = ($route['body'] ?? null) instanceof SchemaType ? $this->renderType($route['body']) : 'never';
            $methods = implode(' | ', array_map(fn(string $m): string => $this->quote(strtoupper($m)), $route['methods']));
            $out[] = sprintf('  %s: ApiRoute<%s, %s, %s, %s, %s>;', $this->quote($route['name']), $this->renderParams($route['pathParams'] ?? []), $this->renderParams($route['queryParams'] ?? []), $body, $this->renderType($route['response']), $methods);
        }
        $out[] = '};'; $out[] = ''; $out[] = 'export const routes = {';
        foreach ($routes as $route) {
            $methods = count($route['methods']) === 1 ? $this->quote(strtoupper($route['methods'][0])) : '[' . implode(', ', array_map(fn(string $m): string => $this->quote(strtoupper($m)), $route['methods'])) . ']';
            $out[] = sprintf('  %s: [%s, %s],', $this->quote($route['name']), $methods, $this->quote($route['path']));
        }
        $out[] = '} as const;'; $out[] = '';
        $out[] = 'const baseAPI = createApi<ApiRoutes>(routes);';
        $out[] = 'export type ApiConfig = Parameters<typeof baseAPI.with>[0];';
        $out[] = '/** Runtime configuration keeps hosts/prefixes out of generated source. */';
        $out[] = 'export const createAPI = (config?: ApiConfig) => config ? baseAPI.with(config) : baseAPI;';
        $out[] = '/** Same-origin default; use createAPI({ baseUrl: ... }) for another origin or path prefix. */';
        $out[] = 'export const API = baseAPI;'; $out[] = '';
        return implode("\n", $out);
    }
    private function renderParams(array $params): string { if ($params === []) return 'Record<string, never>'; $items=[]; foreach($params as $name=>$type)$items[]=$this->propertyName((string)$name).': '.$this->renderType($type); return '{ '.implode('; ',$items).' }'; }
    private function renderClass(ClassSchema $class): string { $out=['/**']; foreach(preg_split('/\R/',$class->description)?:[] as $line)if($line!=='')$out[]=' * '.str_replace('*/','* /',$line); $out[]=' * @php '.$class->className; $out[]=' */'; $out[]='export interface '.$class->shortName.' {'; foreach($class->properties as $property){if($property->description!=='')$out[]='  /** '.str_replace('*/','* /',$property->description).' */';$optional=$property->hasDefaultValue?'?':'';$type=$this->renderType($property->type);if($property->allowsNull&&!str_contains($type,'null'))$type.=' | null';$out[]=sprintf('  %s%s: %s;',$this->propertyName($property->name),$optional,$type);} $out[]='}';return implode("\n",$out); }
    private function renderType(SchemaType $type): string { if($type instanceof PrimitiveSchemaType)return match($type->getKind()){'int','float','numeric'=>'number','bool'=>'boolean','null'=>'null','mixed','object','callable','iterable','resource','scalar'=>'unknown','false','true'=>$type->getKind(),'string'=>'string',default=>'unknown'}; if($type instanceof ArraySchemaType){$value=$this->renderType($type->valueType);return $type->arrayKind===ArraySchemaType::KIND_MAP?'Record<string, '.$value.'>':'Array<'.$value.'>';} if($type instanceof ClassReferenceSchemaType){$name=(string)($type->toArray()['className']??'unknown');$parts=explode('\\',$name);return end($parts)?:'unknown';} if($type instanceof UnionSchemaType||$type instanceof IntersectionSchemaType){$operator=$type instanceof UnionSchemaType?' | ':' & ';return implode($operator,array_map(fn(SchemaType $item):string=>$this->renderType($item),$type->types));} if($type instanceof ClassSchema)return $type->shortName; return 'unknown'; }
    private function propertyName(string $value): string { return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/',$value)?$value:$this->quote($value); }
    private function quote(string $value): string { return json_encode($value,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES); }
}
