<?php

declare(strict_types=1);

namespace Brace\SpaServe\Codegen;

use Phore\Schema\Schema\ClassSchema;
use Phore\Schema\Schema\Type\ArraySchemaType;
use Phore\Schema\Schema\Type\ClassReferenceSchemaType;
use Phore\Schema\Schema\Type\EnumSchemaType;
use Phore\Schema\Schema\Type\IntersectionSchemaType;
use Phore\Schema\Schema\Type\PrimitiveSchemaType;
use Phore\Schema\Schema\Type\SchemaType;
use Phore\Schema\Schema\Type\UnionSchemaType;

final class TypeScriptApiStubGenerator
{
    /**
     * Generate the TypeScript contract and compact route table for @trunkjs/api-stub.
     *
     * @param list<array{name:string,path:string,methods:list<string>,response:SchemaType,body?:SchemaType|null,pathParams?:array<string,SchemaType>,queryParams?:array<string,SchemaType>}> $routes
     * @param list<ClassSchema> $classes
     * @return string Generated TypeScript module.
     * @throws \InvalidArgumentException When route names conflict or DTO names are ambiguous.
     * @see \Brace\SpaServe\Codegen\TypeScriptApiStubModule::load()
     * @example $source = $generator->generate([['name' => 'User.Get', 'path' => '/api/users/{id}', 'methods' => ['GET'], 'response' => $schema]]);
     */
    public function generate(array $routes, array $classes = []): string
    {
        usort($routes, static fn (array $a, array $b): int => $a['name'] <=> $b['name']);
        usort($classes, static fn (ClassSchema $a, ClassSchema $b): int => $a->className <=> $b->className);

        $names = [];
        $tree = [];
        foreach ($classes as $class) {
            if (isset($names[$class->shortName]) && $names[$class->shortName] !== $class->className) {
                throw new \InvalidArgumentException("DTO name '{$class->shortName}' is ambiguous: {$names[$class->shortName]} and {$class->className}");
            }
            $names[$class->shortName] = $class->className;
        }
        foreach ($routes as $route) {
            $parts = explode('.', $route['name']);
            $branch = &$tree;
            foreach ($parts as $index => $part) {
                if ($part === '' || in_array($part, ['with', 'defaults', 'use', 'path', 'url', 'raw', 'request'], true)) {
                    throw new \InvalidArgumentException("Invalid API route name: {$route['name']}");
                }
                if ($index === count($parts) - 1) {
                    if (isset($branch[$part])) {
                        throw new \InvalidArgumentException("Duplicate or conflicting API route: {$route['name']}");
                    }
                    $branch[$part] = $route;
                } else {
                    if (isset($branch[$part]) && isset($branch[$part]['name']) && is_string($branch[$part]['name'])) {
                        throw new \InvalidArgumentException("Conflicting API route: {$route['name']}");
                    }
                    $branch[$part] ??= [];
                    $branch = &$branch[$part];
                }
            }
            unset($branch);
        }

        $out = ['// Generated by brace/mod-spaserve. Do not edit.', "import { createApi, type ApiRoute } from '@trunkjs/api-stub';", ''];
        foreach ($classes as $class) {
            $out[] = $this->renderClass($class);
            $out[] = '';
        }
        $out[] = 'export type ApiRoutes = {';
        $out = [...$out, ...$this->renderRoutes($tree, 1)];
        $out[] = '};';
        $out[] = '';
        $out[] = 'export const routes = {';
        foreach ($routes as $route) {
            $methods = count($route['methods']) === 1
                ? $this->quote(strtoupper($route['methods'][0]))
                : '[' . implode(', ', array_map(fn (string $method): string => $this->quote(strtoupper($method)), $route['methods'])) . ']';
            $out[] = sprintf('  %s: [%s, %s],', $this->quote($route['name']), $methods, $this->quote($route['path']));
        }
        $out[] = '} as const;';
        $out[] = '';
        $out[] = 'const baseAPI = createApi<ApiRoutes>(routes);';
        $out[] = 'export type ApiConfig = Parameters<typeof baseAPI.with>[0];';
        $out[] = 'export const createAPI = (config?: ApiConfig) => config ? baseAPI.with(config) : baseAPI;';
        $out[] = 'export const API = baseAPI;';
        $out[] = '';

        return implode("\n", $out);
    }

    private function renderRoutes(array $tree, int $depth): array
    {
        $out = [];
        foreach ($tree as $name => $entry) {
            $indent = str_repeat('  ', $depth);
            if (!isset($entry['name']) || !is_string($entry['name'])) {
                $out[] = $indent . $this->quote($name) . ': {';
                $out = [...$out, ...$this->renderRoutes($entry, $depth + 1)];
                $out[] = $indent . '};';
                continue;
            }

            $body = ($entry['body'] ?? null) instanceof SchemaType ? $this->renderType($entry['body']) : 'never';
            $methods = implode(' | ', array_map(fn (string $method): string => $this->quote(strtoupper($method)), $entry['methods']));
            $out[] = sprintf('%s%s: ApiRoute<%s, %s, %s, %s, %s>;', $indent, $this->quote($name), $this->renderParams($entry['pathParams'] ?? []), $this->renderParams($entry['queryParams'] ?? []), $body, $this->renderType($entry['response']), $methods);
        }

        return $out;
    }

    private function renderParams(array $params): string
    {
        if ($params === []) {
            return 'Record<string, never>';
        }
        $items = [];
        foreach ($params as $name => $type) {
            $items[] = $this->propertyName((string) $name) . ': ' . $this->renderType($type);
        }
        return '{ ' . implode('; ', $items) . ' }';
    }

    private function renderClass(ClassSchema $class): string
    {
        $out = ['/**'];
        foreach (preg_split('/\R/', $class->description) ?: [] as $line) {
            if ($line !== '') {
                $out[] = ' * ' . str_replace('*/', '* /', $line);
            }
        }
        $out[] = ' * @php ' . $class->className;
        $out[] = ' */';
        $out[] = 'export interface ' . $class->shortName . ' {';
        foreach ($class->properties as $property) {
            if ($property->description !== '') {
                $out[] = '  /** ' . str_replace('*/', '* /', $property->description) . ' */';
            }
            $type = $this->renderType($property->type);
            if ($property->allowsNull && !str_contains($type, 'null')) {
                $type .= ' | null';
            }
            $out[] = sprintf('  %s%s: %s;', $this->propertyName($property->name), $property->hasDefaultValue ? '?' : '', $type);
        }
        $out[] = '}';
        return implode("\n", $out);
    }

    private function renderType(SchemaType $type): string
    {
        if ($type instanceof PrimitiveSchemaType) {
            return match ($type->getKind()) {
                'int', 'float', 'numeric' => 'number',
                'bool' => 'boolean',
                'null' => 'null',
                'false', 'true' => $type->getKind(),
                'string' => 'string',
                'void' => 'undefined',
                default => 'unknown',
            };
        }
        if ($type instanceof ArraySchemaType) {
            $value = $this->renderType($type->valueType);
            return $type->arrayKind === ArraySchemaType::KIND_MAP ? 'Record<string, ' . $value . '>' : 'Array<' . $value . '>';
        }
        if ($type instanceof EnumSchemaType) {
            return implode(' | ', array_map(fn (array $case): string => $this->quote($case['value']), $type->cases));
        }
        if ($type instanceof ClassReferenceSchemaType) {
            $parts = explode('\\', $type->className);
            return end($parts) ?: 'unknown';
        }
        if ($type instanceof UnionSchemaType || $type instanceof IntersectionSchemaType) {
            $operator = $type instanceof UnionSchemaType ? ' | ' : ' & ';
            return implode($operator, array_map(fn (SchemaType $item): string => $this->renderType($item), $type->types));
        }
        return $type instanceof ClassSchema ? $type->shortName : 'unknown';
    }

    private function propertyName(string $value): string
    {
        return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $value) ? $value : $this->quote($value);
    }

    private function quote(string $value): string
    {
        return json_encode($value, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
    }
}
